# netlify.toml

[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about/*"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/projects/index.html"
  status = 200

[[redirects]]
  from = "/articles/*"
  to = "/articles/index.html"
  status = 200

[[redirects]]
  from = "/article/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
